<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Desktop-Monitor-2nd-Floor-Room3" failures="1" tests="3" name="com.actitime.testscript.CustomerModule" time="2.071" errors="0" timestamp="2024-03-05T09:23:41 IST" skipped="1">
  <testcase classname="com.actitime.testscript.CustomerModule" name="modifyCustomer" time="0.826">
    <skipped/>
    <system-out>
      <![CDATA[modifyCustomer has got skipped]]>
    </system-out>
  </testcase> <!-- modifyCustomer -->
  <testcase classname="com.actitime.testscript.CustomerModule" name="createCustomer" time="1.242">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at com.actitime.testscript.CustomerModule.createCustomer(CustomerModule.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[createCustomer has got failed]]>
    </system-out>
  </testcase> <!-- createCustomer -->
  <testcase classname="com.actitime.testscript.CustomerModule" name="deleteCustomer" time="0.003">
    <system-out>
      <![CDATA[deleteCustomer
deleteCustomer has got passed]]>
    </system-out>
  </testcase> <!-- deleteCustomer -->
  <system-out>
    <![CDATA[openBrowser
login
createCustomer has got failed
logout
login
deleteCustomer
deleteCustomer has got passed
logout
modifyCustomer has got skipped
closeBrowser]]>
  </system-out>
</testsuite> <!-- com.actitime.testscript.CustomerModule -->
